services:
  bot:
    build: 
      context: .
      args:
        - DOCKER_UID=${DOCKER_UID:-1000}
        - DOCKER_GID=${DOCKER_GID:-1000}
    container_name: telegram-publisher-bot
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env:ro
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=UTC
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"