services:
  bot:
    build: .
    container_name: telegram-publisher-bot
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env:ro
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=UTC
      - CREATED_BY=gopnikgame
      - CREATED_AT=2025-02-24_18:20:11