version: '3.8'

services:
  bot:
    build: .
    container_name: telegram-publisher-bot
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1