version: "3.9"
services:
  telegram-publisher-bot:
    image: telegram-publisher-bot
    build: .
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      ADMIN_IDS: ${ADMIN_IDS}
      CHANNEL_ID: ${CHANNEL_ID}
      DEFAULT_FORMAT: ${DEFAULT_FORMAT}
      MAX_FILE_SIZE: ${MAX_FILE_SIZE}
      MAIN_BOT_NAME: ${MAIN_BOT_NAME}
      MAIN_BOT_LINK: ${MAIN_BOT_LINK}
      SUPPORT_BOT_NAME: ${SUPPORT_BOT_NAME}
      SUPPORT_BOT_LINK: ${SUPPORT_BOT_LINK}
      CHANNEL_NAME: ${CHANNEL_NAME}
      CHANNEL_LINK: ${CHANNEL_LINK}
      TEST_MODE: ${TEST_MODE}
      TEST_CHAT_ID: ${TEST_CHAT_ID}
      HTTPS_PROXY: ${HTTPS_PROXY}
    volumes:
      - ./logs:/app/logs
    restart: always